"""empty message

Revision ID: 303ad356acef
Revises: 7b224ea62dae
Create Date: 2026-03-27 15:11:17.308484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303ad356acef'
down_revision: Union[str, Sequence[str], None] = '7b224ea62dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campeonatos', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('campeonatos', 'data_fim',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campeonatos', 'data_fim',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('campeonatos', 'status')
    # ### end Alembic commands ###
