"""Criacao da Tabela EventoParticipante e papeis_evento_participante

Revision ID: 3ac8767d9a90
Revises: 83aa97ad5ad5
Create Date: 2026-03-30 22:07:37.223437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac8767d9a90'
down_revision: Union[str, Sequence[str], None] = '83aa97ad5ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papeis_evento_participante',
    sa.Column('id_papel', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_papel')
    )
    op.create_index(op.f('ix_papeis_evento_participante_id_papel'), 'papeis_evento_participante', ['id_papel'], unique=False)
    op.create_table('eventos_participante',
    sa.Column('id_evento_participante', sa.Integer(), nullable=False),
    sa.Column('id_evento_jogo', sa.Integer(), nullable=False),
    sa.Column('id_time', sa.Integer(), nullable=False),
    sa.Column('id_jogador_time', sa.Integer(), nullable=True),
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento_jogo'], ['eventos_jogo.id_evento_jogo'], ),
    sa.ForeignKeyConstraint(['id_jogador_time'], ['jogadores_times.id_jogador_time'], ),
    sa.ForeignKeyConstraint(['id_time'], ['times.id_time'], ),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis_evento_participante.id_papel'], ),
    sa.PrimaryKeyConstraint('id_evento_participante')
    )
    op.create_index(op.f('ix_eventos_participante_id_evento_participante'), 'eventos_participante', ['id_evento_participante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_participante_id_evento_participante'), table_name='eventos_participante')
    op.drop_table('eventos_participante')
    op.drop_index(op.f('ix_papeis_evento_participante_id_papel'), table_name='papeis_evento_participante')
    op.drop_table('papeis_evento_participante')
    # ### end Alembic commands ###
