"""Criacao da Tabela EventoParticipante

Revision ID: 83aa97ad5ad5
Revises: afe48dc35163
Create Date: 2026-03-30 22:01:58.813626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83aa97ad5ad5'
down_revision: Union[str, Sequence[str], None] = 'afe48dc35163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
