"""empty message

Revision ID: 8ee7395c34d3
Revises: 0a8eebc446b1
Create Date: 2026-04-02 22:25:22.822396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee7395c34d3'
down_revision: Union[str, Sequence[str], None] = '0a8eebc446b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_evento', sa.Column('acao_slug', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_evento', 'acao_slug')
    # ### end Alembic commands ###
