"""Alteracao na tabela EventoJogo

Revision ID: afe48dc35163
Revises: 303ad356acef
Create Date: 2026-03-30 21:51:51.610544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe48dc35163'
down_revision: Union[str, Sequence[str], None] = '303ad356acef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('eventos_jogo_id_jogador_principal_fkey'), 'eventos_jogo', type_='foreignkey')
    op.drop_constraint(op.f('eventos_jogo_id_jogador_relacionado_fkey'), 'eventos_jogo', type_='foreignkey')
    op.drop_constraint(op.f('eventos_jogo_id_time_fkey'), 'eventos_jogo', type_='foreignkey')
    op.drop_column('eventos_jogo', 'id_time')
    op.drop_column('eventos_jogo', 'id_jogador_principal')
    op.drop_column('eventos_jogo', 'id_jogador_relacionado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos_jogo', sa.Column('id_jogador_relacionado', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('eventos_jogo', sa.Column('id_jogador_principal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('eventos_jogo', sa.Column('id_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('eventos_jogo_id_time_fkey'), 'eventos_jogo', 'times', ['id_time'], ['id_time'])
    op.create_foreign_key(op.f('eventos_jogo_id_jogador_relacionado_fkey'), 'eventos_jogo', 'jogadores_times', ['id_jogador_relacionado'], ['id_jogador_time'])
    op.create_foreign_key(op.f('eventos_jogo_id_jogador_principal_fkey'), 'eventos_jogo', 'jogadores_times', ['id_jogador_principal'], ['id_jogador_time'])
    # ### end Alembic commands ###
