"""Initial Migration

Revision ID: bbee233d48c0
Revises: 
Create Date: 2026-03-17 00:06:58.547392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbee233d48c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campeonatos',
    sa.Column('id_campeonato', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_campeonato')
    )
    op.create_index(op.f('ix_campeonatos_id_campeonato'), 'campeonatos', ['id_campeonato'], unique=False)
    op.create_table('estadio',
    sa.Column('id_estadio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_estadio')
    )
    op.create_index(op.f('ix_estadio_id_estadio'), 'estadio', ['id_estadio'], unique=False)
    op.create_table('jogadores',
    sa.Column('id_jogador', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('posicao', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_jogador')
    )
    op.create_index(op.f('ix_jogadores_id_jogador'), 'jogadores', ['id_jogador'], unique=False)
    op.create_table('times',
    sa.Column('id_time', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_time')
    )
    op.create_index(op.f('ix_times_id_time'), 'times', ['id_time'], unique=False)
    op.create_table('tipos_evento',
    sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_evento')
    )
    op.create_index(op.f('ix_tipos_evento_id_tipo_evento'), 'tipos_evento', ['id_tipo_evento'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('jogadores_times',
    sa.Column('id_jogador_time', sa.Integer(), nullable=False),
    sa.Column('id_jogador', sa.Integer(), nullable=False),
    sa.Column('id_time', sa.Integer(), nullable=False),
    sa.Column('id_campeonato', sa.Integer(), nullable=False),
    sa.Column('numero_camisa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_campeonato'], ['campeonatos.id_campeonato'], ),
    sa.ForeignKeyConstraint(['id_jogador'], ['jogadores.id_jogador'], ),
    sa.ForeignKeyConstraint(['id_time'], ['times.id_time'], ),
    sa.PrimaryKeyConstraint('id_jogador_time')
    )
    op.create_index(op.f('ix_jogadores_times_id_jogador_time'), 'jogadores_times', ['id_jogador_time'], unique=False)
    op.create_table('jogos',
    sa.Column('id_jogo', sa.Integer(), nullable=False),
    sa.Column('id_time_casa', sa.Integer(), nullable=False),
    sa.Column('id_time_visitante', sa.Integer(), nullable=False),
    sa.Column('id_campeonato', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.Date(), nullable=False),
    sa.Column('fase', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('gols_time_casa', sa.Integer(), nullable=True),
    sa.Column('gols_time_visitante', sa.Integer(), nullable=True),
    sa.Column('id_estadio', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_campeonato'], ['campeonatos.id_campeonato'], ),
    sa.ForeignKeyConstraint(['id_estadio'], ['estadio.id_estadio'], ),
    sa.ForeignKeyConstraint(['id_time_casa'], ['times.id_time'], ),
    sa.ForeignKeyConstraint(['id_time_visitante'], ['times.id_time'], ),
    sa.PrimaryKeyConstraint('id_jogo')
    )
    op.create_index(op.f('ix_jogos_id_jogo'), 'jogos', ['id_jogo'], unique=False)
    op.create_table('times_campeonato',
    sa.Column('id_time_campeonato', sa.Integer(), nullable=False),
    sa.Column('id_time', sa.Integer(), nullable=False),
    sa.Column('id_campeonato', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_campeonato'], ['campeonatos.id_campeonato'], ),
    sa.ForeignKeyConstraint(['id_time'], ['times.id_time'], ),
    sa.PrimaryKeyConstraint('id_time_campeonato')
    )
    op.create_index(op.f('ix_times_campeonato_id_time_campeonato'), 'times_campeonato', ['id_time_campeonato'], unique=False)
    op.create_table('escalacoes',
    sa.Column('id_escalacao', sa.Integer(), nullable=False),
    sa.Column('id_jogo', sa.Integer(), nullable=False),
    sa.Column('id_jogador', sa.Integer(), nullable=False),
    sa.Column('titular', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_jogador'], ['jogadores_times.id_jogador_time'], ),
    sa.ForeignKeyConstraint(['id_jogo'], ['jogos.id_jogo'], ),
    sa.PrimaryKeyConstraint('id_escalacao')
    )
    op.create_index(op.f('ix_escalacoes_id_escalacao'), 'escalacoes', ['id_escalacao'], unique=False)
    op.create_table('eventos_jogo',
    sa.Column('id_evento_jogo', sa.Integer(), nullable=False),
    sa.Column('id_jogo', sa.Integer(), nullable=False),
    sa.Column('id_time', sa.Integer(), nullable=False),
    sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
    sa.Column('id_jogador_principal', sa.Integer(), nullable=True),
    sa.Column('id_jogador_relacionado', sa.Integer(), nullable=True),
    sa.Column('minuto_ocorrido', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_jogador_principal'], ['jogadores_times.id_jogador_time'], ),
    sa.ForeignKeyConstraint(['id_jogador_relacionado'], ['jogadores_times.id_jogador_time'], ),
    sa.ForeignKeyConstraint(['id_jogo'], ['jogos.id_jogo'], ),
    sa.ForeignKeyConstraint(['id_time'], ['times.id_time'], ),
    sa.ForeignKeyConstraint(['id_tipo_evento'], ['tipos_evento.id_tipo_evento'], ),
    sa.PrimaryKeyConstraint('id_evento_jogo')
    )
    op.create_index(op.f('ix_eventos_jogo_id_evento_jogo'), 'eventos_jogo', ['id_evento_jogo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_jogo_id_evento_jogo'), table_name='eventos_jogo')
    op.drop_table('eventos_jogo')
    op.drop_index(op.f('ix_escalacoes_id_escalacao'), table_name='escalacoes')
    op.drop_table('escalacoes')
    op.drop_index(op.f('ix_times_campeonato_id_time_campeonato'), table_name='times_campeonato')
    op.drop_table('times_campeonato')
    op.drop_index(op.f('ix_jogos_id_jogo'), table_name='jogos')
    op.drop_table('jogos')
    op.drop_index(op.f('ix_jogadores_times_id_jogador_time'), table_name='jogadores_times')
    op.drop_table('jogadores_times')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_evento_id_tipo_evento'), table_name='tipos_evento')
    op.drop_table('tipos_evento')
    op.drop_index(op.f('ix_times_id_time'), table_name='times')
    op.drop_table('times')
    op.drop_index(op.f('ix_jogadores_id_jogador'), table_name='jogadores')
    op.drop_table('jogadores')
    op.drop_index(op.f('ix_estadio_id_estadio'), table_name='estadio')
    op.drop_table('estadio')
    op.drop_index(op.f('ix_campeonatos_id_campeonato'), table_name='campeonatos')
    op.drop_table('campeonatos')
    # ### end Alembic commands ###
