"""Adicao de novas colunas em jogo para controle de eventos em tempo real

Revision ID: d4274ff7bfb1
Revises: 8ee7395c34d3
Create Date: 2026-04-04 10:22:48.549655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4274ff7bfb1'
down_revision: Union[str, Sequence[str], None] = '8ee7395c34d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogos', sa.Column('status', sa.String(), nullable=False))
    op.add_column('jogos', sa.Column('inicio_real', sa.DateTime(), nullable=True))
    op.add_column('jogos', sa.Column('fim_real', sa.DateTime(), nullable=True))
    op.alter_column('jogos', 'data_hora',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jogos', 'data_hora',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('jogos', 'fim_real')
    op.drop_column('jogos', 'inicio_real')
    op.drop_column('jogos', 'status')
    # ### end Alembic commands ###
